# Generated by Django 5.2 on 2025-04-10 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
