# Generated by Django 5.2 on 2025-04-24 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected_attributes',
            field=models.CharField(blank=True, help_text='Selected attributes (e.g., color)', max_length=255),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='selected_size',
            field=models.CharField(blank=True, help_text='Selected size for fashion products', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_attributes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='selected_size',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.CharField(blank=True, help_text='Comma-separated attributes (e.g., color, material)', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(blank=True, help_text='Comma-separated sizes for fashion products (e.g., S,M,L,XL)', max_length=100),
        ),
        migrations.AddField(
            model_name='sellerproductsubmission',
            name='attributes',
            field=models.CharField(blank=True, help_text='Comma-separated attributes (e.g., color, material)', max_length=255),
        ),
        migrations.AddField(
            model_name='sellerproductsubmission',
            name='available_sizes',
            field=models.CharField(blank=True, help_text='Comma-separated sizes for fashion products (e.g., S,M,L,XL)', max_length=100),
        ),
    ]
