# Generated by Django 5.2 on 2025-05-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_cartitem_selected_attributes_cartitem_selected_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Fallback description if Flask API unavailable'),
        ),
    ]
