# Generated by Django 5.2 on 2025-05-04 21:30

import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[store.models.validate_discount]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[store.models.validate_discount]),
        ),
        migrations.AlterField(
            model_name='sellerproductsubmission',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[store.models.validate_discount]),
        ),
        migrations.AlterField(
            model_name='sellerproductsubmission',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
